### ISSUE TITLE
Disable default column toggling UI

### ISSUE THREAD

**Issue by robin-dongbin** [icflorescu/mantine-datatable#701]
**Is your feature request related to a problem? Please describe.**
Is it possible to add a property to turn off the default column toggling UI? This would include the close button on the column, and the context menu on the header.

I like `useDataTableColumns` hook. I think I can easily customize my column toggling UI related logic with this hook

**Describe the solution you'd like**
A prop to disable default column toggling UI

**Describe alternatives you've considered**
I don't think there's any other more convenient way

**Additional context**

**Comment by ebalo55** [comment]
With just a bit of CSS and custom styling, you can achieve this.

```css
.mantine-Popover-dropdown {
    /* Customize your dropdown style if you want */

    &:has(.mantine-datatable-header-column-toggle-checkbox-label) {
        display: none;
    }
}
```
